apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1USXhOVEE1TWpJeU1Wb1hEVE16TVRJeE1qQTVNamN5TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGNzCjl1MTNRNnR6Ry9yUGNvQjN5dHhpMndma2ZtZWFHclFRV0pZS0NFOEFlMmZCTUhNc2VmY0NkdGYvTjNMUGQyZGwKVUJWajBwTVBHTisvc0YySHRFN1RXMFoxL091a1poVy93a3hUQ3ZsUHp5Qzdud09aOVAyUUpNRXBKNE5hK2JBZgp2anV6TFpBZEh2MUtXMVFNajZGdnVVdmJjeWExbWdrZDlkcXZvREQxN2ZyNmtXejk2REhhZjZmYUE5eXQ0K1M4Ckp0ZXdiV2Y2bVREV2pUcUVYTWJ3RE0yWEFIbHM5N0xDZFU5OFhlZkMzWDlyQ0tub2F1b254N2VxeHNHVnpkbUQKSUY2TnN2Y2tRdVRuOThUU1dYNUZldnhRRjBFUmdmS0JxZWpCR0xDVVVVR21NM29LWmJMV0R5bXE2WjdCREx3LwpBVyswMDdGbnhjc2s5ZlVhcnI4Q0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGTm51aGhXRjRRelA0YzZxK3JPamRvQjA2N3puTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQ1VlQVNJZThrUkhpUG5JQnowdlV3VDYwUGc1aGZONGl6MHdSbkRLTXNmTzZQegp0bXE5Rkc3cEFwVVFOSlJtMUsvejhyNDBUMjE4Z205NFhVU1YzMjZnLzZpNU5valRnd0pRd2lNSWhwRldBWllqCkh3M1R1bmNSaVV3ZTlMcTZOcHpUQ1NBanMzR0FZemh6WHpIdWlDNHoxa2dDZ2R5S0plOFh0SEZDaWJlM2RuZlIKQXFYb1dTQmVzVng5NVppUDBhTlg4Y0tmaDJkcTVkaDZNcE1wOUdvKzVYeVdiUXY5R01BUHIwNTJ4TEVLTEJ4TwpCTXViaWlOUHF0c2Zjc2MvMVIvV2VaWFhwS1gwNTM5WXdOU0tMdDdPRDBXdlhLMHVPaHpmbGwvZk1YNTUwcGtpCkJoZ1FMNXRQWXl3cFZsb2pBZytzcWY1WnAwNmlXZlY0QzMwSzZIdXQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://b85b37e3-bcf7-4e5b-aa14-71bf4d1816cd-public.ke.kr-central-2.kakaocloud.com
  name: ahn-cluster
contexts:
- context:
    cluster: ahn-cluster
    user: ahn-cluster-admin
  name: ahn-cluster-admin@ahn-cluster
current-context: ahn-cluster-admin@ahn-cluster
kind: Config
preferences: {}
users:
- name: ahn-cluster-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoi.io/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "9f85599ab2d242b892ed820927ca9372"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "oDHyYkQrtrHQDYO1RqOgM81SwXbstT_0ygkNuaEpdFjteQX5yAO7puMEju8QEDRVWR66JsZMZao_bEx7BgHTJQ"
      - name: "OS_REGION_NAME"
        value: "kr-central-2"
      provideClusterInfo: false
